# A minimal HTTP/3 server built on aioquic's low-level H3 API, added to the
# interop matrix as a THIRD, genuinely independent stack. Its value is a third
# independent QUIC transport + H3 implementation — aioquic's own ACK strategy,
# MAX_STREAMS replenishment (the 300-request SequentialReuse test leans on it),
# flow-control update cadence, and handshake shape — distinct from Caddy's quic-go
# and nginx's C stack. (Its QPACK is ls-qpack via pylsqpack, a third encoder; but
# against a capacity-0 client it encodes static-only, where the three stacks'
# byte output nearly coincides, so the marginal QPACK-decode coverage is small —
# the transport-layer diversity is the real win.)
#
# It is deliberately NOT the Starlette-based examples/http3_server.py demo app —
# this is ~90 lines serving the exact route contract the interop tests assert
# (see http3/interop_test.go), so the oracles stay byte-exact:
#   GET/POST/HEAD /            -> 200, a small canned body (+ Content-Length)
#   GET /big.txt               -> 200, the 16 KiB fixture (byte-for-byte)
#   GET /huge.txt              -> 200, the 1 MiB fixture (spans the key update)
#   GET /status/{204,304}      -> that status, no body (the no-content carve-outs)
#   GET /status/{404,500}      -> that status, a body + matching Content-Length
#
# The client skips certificate verification, so the self-signed cert generated by
# the compose `certs` service is sufficient. Env: CERT/KEY (default /certs/*.pem),
# ADDR host/PORT (default 0.0.0.0:443), SRV fixture root (default /srv).

import asyncio
import os

from aioquic.asyncio import serve
from aioquic.asyncio.protocol import QuicConnectionProtocol
from aioquic.h3.connection import H3Connection
from aioquic.h3.events import DataReceived, HeadersReceived
from aioquic.quic.configuration import QuicConfiguration
from aioquic.quic.events import ProtocolNegotiated

SRV = os.environ.get("SRV", "/srv")
CANNED = b"hello from http3 aioquic\n"


def route(path):
    """Map a request path to (status, body). body is None for a bodyless status
    (204/304); otherwise the exact bytes to send (and to size Content-Length by,
    even for HEAD, where the bytes themselves are suppressed)."""
    if path == "/":
        return 200, CANNED
    if path == "/status/204":
        return 204, None
    if path == "/status/304":
        return 304, None
    if path == "/status/404":
        return 404, b"not found\n"
    if path == "/status/500":
        return 500, b"boom\n"
    if path in ("/big.txt", "/huge.txt"):
        try:
            with open(SRV + path, "rb") as f:
                return 200, f.read()
        except OSError:
            return 404, b"not found\n"
    return 404, b"not found\n"


class H3Server(QuicConnectionProtocol):
    """Serves one QUIC connection: builds an H3Connection once ALPN "h3" is
    negotiated, then answers each request stream from the route table above."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._http = None
        self._method = {}  # stream_id -> request method
        self._path = {}    # stream_id -> request :path

    def quic_event_received(self, event):
        if isinstance(event, ProtocolNegotiated) and event.alpn_protocol == "h3":
            # H3Connection opens the server's control + QPACK streams itself.
            self._http = H3Connection(self._quic)
        if self._http is None:
            return
        for e in self._http.handle_event(event):
            self._h3_event(e)

    def _h3_event(self, e):
        if isinstance(e, HeadersReceived):
            for name, value in e.headers:
                if name == b":method":
                    self._method[e.stream_id] = value.decode()
                elif name == b":path":
                    self._path[e.stream_id] = value.decode()
            if e.stream_ended:  # a bodyless request (GET/HEAD): answer now
                self._respond(e.stream_id)
        elif isinstance(e, DataReceived) and e.stream_ended:
            # A request with a body (POST): the body is consumed and ignored; the
            # response is sent once the request stream is complete.
            self._respond(e.stream_id)

    def _respond(self, stream_id):
        method = self._method.pop(stream_id, "GET")
        path = self._path.pop(stream_id, "/")
        status, body = route(path)

        headers = [(b":status", str(status).encode())]
        if body is not None:
            headers.append((b"content-length", str(len(body)).encode()))
            headers.append((b"content-type", b"text/plain"))

        # HEAD carries the head (including Content-Length) but no body (RFC 9110
        # §9.3.2); 204/304 have no body by definition. Everything else sends its
        # body and ends the stream on the DATA frame.
        send_body = body is not None and body != b"" and method != "HEAD"
        self._http.send_headers(stream_id=stream_id, headers=headers, end_stream=not send_body)
        if send_body:
            self._http.send_data(stream_id=stream_id, data=body, end_stream=True)
        self.transmit()


async def main():
    config = QuicConfiguration(is_client=False, alpn_protocols=["h3"])
    config.load_cert_chain(
        os.environ.get("CERT", "/certs/cert.pem"),
        os.environ.get("KEY", "/certs/key.pem"),
    )
    host = os.environ.get("ADDR", "0.0.0.0")
    port = int(os.environ.get("PORT", "443"))
    await serve(host, port, configuration=config, create_protocol=H3Server)
    # Signal readiness for the compose healthcheck: serve() returns once the UDP
    # socket is bound, so the runner (gated on service_healthy) starts only after
    # the pip-install-then-listen startup completes — no raised dial timeout.
    with open("/tmp/ready", "w"):
        pass
    print(f"aioquic h3 server listening {host}:{port}", flush=True)
    await asyncio.Future()  # run forever


if __name__ == "__main__":
    asyncio.run(main())
