FROM alpine:3.20 AS builder

RUN apk add --no-cache \
    build-base cmake autoconf automake libtool git \
    openssl-dev openssl-libs-static zlib-dev zlib-static \
    c-ares-dev libev-dev libevent-dev jansson-dev \
    libxml2-dev boost-dev brotli-dev

RUN git clone --depth=1 --branch v1.68.0 https://github.com/nghttp2/nghttp2.git /nghttp2

WORKDIR /nghttp2

RUN git submodule update --init --depth=1

RUN autoreconf -i && \
    ./configure \
        --disable-examples \
        --disable-hpack-tools \
        --disable-python-bindings \
        --enable-app \
        --with-openssl \
        --without-jemalloc && \
    make -j$(nproc) && \
    make install

FROM alpine:3.20

RUN apk add --no-cache \
    openssl-libs zlib libev libevent jansson libxml2 \
    c-ares brotli libstdc++ wget

COPY --from=builder /usr/local/bin/nghttpx /usr/local/bin/nghttpx

ENTRYPOINT ["nghttpx"]
